export const categoryTemplate: any = {
  saree: [
    { header: "styleId", key: "styleId", width: 20 },
    { header: "styleGroupId", key: "styleGroupId", width: 20 },
    { header: "vendorSkuCode", key: "vendorSkuCode", width: 30 },
    { header: "vendorArticleNumber", key: "vendorArticleNumber", width: 25 },
    { header: "Product Title", key: "productTitle", width: 30 },
    { header: "brand", key: "brand", width: 20 },
    { header: "Product Description", key: "productDescription", width: 30 },
    {
      header: "Manufacturer Name and Address with Pincode",
      key: "manufacturer",
      width: 40,
    },
    {
      header: "Packer Name and Address with Pincode",
      key: "packer",
      width: 40,
    },
    {
      header: "Importer Name and Address with Pincode",
      key: "importer",
      width: 40,
    },
    { header: "Country Of Origin", key: "countryOfOrigin", width: 20 },
    { header: "articleType", key: "articleType", width: 25 },
    { header: "Brand Size", key: "brandSize", width: 20 },
    { header: "Standard Size", key: "standardSize", width: 20 },
    {
      header: "is Standard Size present on Label",
      key: "isStandardSize",
      width: 25,
    },
    { header: "Brand Colour (Remarks)", key: "brandColor", width: 25 },
    { header: "GTIN", key: "gtin", width: 20 },
    { header: "HSN", key: "hsn", width: 20 },
    { header: "SKUCode", key: "skuCode", width: 20 },
    { header: "MRP", key: "mrp", width: 15 },
    { header: "AgeGroup", key: "ageGroup", width: 15 },
    { header: "Prominent Colour", key: "prominentColour", width: 25 },
    {
      header: "Second Prominent Colour",
      key: "secondProminentColour",
      width: 25,
    },
    {
      header: "Third Prominent Colour",
      key: "thirdProminentColour",
      width: 25,
    },
    { header: "FashionType", key: "fashionType", width: 20 },
    { header: "Usage", key: "usage", width: 20 },
    { header: "Year", key: "year", width: 10 },
    { header: "season", key: "season", width: 15 },
    { header: "Product Details", key: "productDetails", width: 40 },
    { header: "sizeAndFitDescription", key: "sizeAndFit", width: 40 },
    { header: "Saree Fabric", key: "sareeFabric", width: 30 },
    { header: "Blouse Fabric", key: "blouseFabric", width: 30 },
    { header: "Blouse", key: "blouse", width: 20 },
    { header: "Pattern", key: "pattern", width: 25 },
    { header: "Wash Care", key: "washCare", width: 30 },
    { header: "Front Image", key: "frontImage", width: 40 },
    { header: "Side Image", key: "sideImage", width: 40 },
    { header: "Back Image", key: "backImage", width: 40 },
    { header: "Detail Angle", key: "detailAngle", width: 40 },
    { header: "Gender", key: "gender", width: 20 },
  ],
  tShirt: [
    { header: "styleId", key: "styleId", width: 20 },
    { header: "styleGroupId", key: "styleGroupId", width: 20 },
    { header: "vendorSkuCode", key: "vendorSkuCode", width: 30 },
    { header: "brand", key: "brand", width: 20 },
    { header: "Product Title", key: "productTitle", width: 30 },
    { header: "Product Description", key: "productDescription", width: 30 },
    { header: "Size", key: "size", width: 15 },
    { header: "Color", key: "color", width: 20 },
    { header: "Material", key: "material", width: 30 },
    { header: "Fit Type", key: "fitType", width: 20 },
    { header: "Neck Type", key: "neckType", width: 25 },
    { header: "Sleeve Type", key: "sleeveType", width: 25 },
    { header: "MRP", key: "mrp", width: 15 },
    { header: "Wash Care", key: "washCare", width: 30 },
    { header: "Front Image", key: "frontImage", width: 40 },
    { header: "Back Image", key: "backImage", width: 40 },
    { header: "Gender", key: "gender", width: 20 },
  ],

  jeans: [
    { header: "styleId", key: "styleId", width: 20 },
    { header: "styleGroupId", key: "styleGroupId", width: 20 },
    { header: "vendorSkuCode", key: "vendorSkuCode", width: 30 },
    { header: "brand", key: "brand", width: 20 },
    { header: "Product Title", key: "productTitle", width: 30 },
    { header: "Product Description", key: "productDescription", width: 30 },
    { header: "Waist Size", key: "waistSize", width: 20 },
    { header: "Length", key: "length", width: 15 },
    { header: "Fit Type", key: "fitType", width: 25 },
    { header: "Color", key: "color", width: 20 },
    { header: "Material", key: "material", width: 30 },
    { header: "Pattern", key: "pattern", width: 25 },
    { header: "Closure", key: "closure", width: 20 },
    { header: "MRP", key: "mrp", width: 15 },
    { header: "Wash Care", key: "washCare", width: 30 },
    { header: "Front Image", key: "frontImage", width: 40 },
    { header: "Back Image", key: "backImage", width: 40 },
    { header: "Gender", key: "gender", width: 20 },
  ],

  kurti: [
    { header: "styleId", key: "styleId", width: 20 },
    { header: "styleGroupId", key: "styleGroupId", width: 20 },
    { header: "vendorSkuCode", key: "vendorSkuCode", width: 30 },
    { header: "brand", key: "brand", width: 20 },
    { header: "Product Title", key: "productTitle", width: 30 },
    { header: "Product Description", key: "productDescription", width: 30 },
    { header: "Size", key: "size", width: 15 },
    { header: "Material", key: "material", width: 30 },
    { header: "Sleeve Type", key: "sleeveType", width: 25 },
    { header: "Neck Type", key: "neckType", width: 25 },
    { header: "Length", key: "length", width: 20 },
    { header: "Work Type", key: "workType", width: 30 },
    { header: "Color", key: "color", width: 20 },
    { header: "MRP", key: "mrp", width: 15 },
    { header: "Wash Care", key: "washCare", width: 30 },
    { header: "Front Image", key: "frontImage", width: 40 },
    { header: "Back Image", key: "backImage", width: 40 },
    { header: "Gender", key: "gender", width: 20 },
  ],

  jacket: [
    { header: "styleId", key: "styleId", width: 20 },
    { header: "styleGroupId", key: "styleGroupId", width: 20 },
    { header: "vendorSkuCode", key: "vendorSkuCode", width: 30 },
    { header: "Product Description", key: "productDescription", width: 30 },
    { header: "brand", key: "brand", width: 20 },
    { header: "Product Title", key: "productTitle", width: 30 },
    { header: "Size", key: "size", width: 15 },
    { header: "Material", key: "material", width: 30 },
    { header: "Closure Type", key: "closureType", width: 25 },
    { header: "Hooded", key: "hooded", width: 15 },
    { header: "Sleeve Type", key: "sleeveType", width: 25 },
    { header: "Color", key: "color", width: 20 },
    { header: "MRP", key: "mrp", width: 15 },
    { header: "Wash Care", key: "washCare", width: 30 },
    { header: "Front Image", key: "frontImage", width: 40 },
    { header: "Back Image", key: "backImage", width: 40 },
    { header: "Gender", key: "gender", width: 20 },
  ],
};
